import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import QRCode from 'qrcode'
import html2canvas from 'html2canvas'

type Item = { name: string; qty?: number; price: number; description?: string; image?: string }
const rupiah = (n: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(n) || 0)
const dateText = (date: string) => date ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'long' }).format(new Date(`${date}T00:00:00`)) : '—'
const today = new Date().toISOString().slice(0, 10)
const cleanPhone = (value: string) => value.replace(/\D/g, '').replace(/^0/, '62')
const encode = (value: unknown) => btoa(unescape(encodeURIComponent(JSON.stringify(value)))).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', '')
const decode = <T,>(hash: string): T | null => { try { const base = hash.replace(/^#/, '').replaceAll('-', '+').replaceAll('_', '/'); return JSON.parse(decodeURIComponent(escape(atob(base)))) as T } catch { return null } }

const tools = [
  ['qris-designer', '▦', 'QRIS Designer'], ['qr-business-card', '▣', 'QR Business Card'], ['invoice', '□', 'Invoice Generator'], ['receipt', '▤', 'Receipt Generator'], ['price-list', '☷', 'Price List Generator'],
  ['qr-menu', '☰', 'QR Menu'], ['catalog', '▧', 'Catalog Maker'], ['whatsapp', '◌', 'WhatsApp Link Generator'], ['google-maps-qr', '⌖', 'Google Maps QR'], ['wifi-qr', '⌁', 'WiFi QR'],
]

function go(path: string) { history.pushState({}, '', path); window.dispatchEvent(new Event('popstate')) }
function download(data: string, name: string) { const a = document.createElement('a'); a.href = data; a.download = name; a.click() }
function copy(text: string) { navigator.clipboard?.writeText(text) }
function print() { window.print() }

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }
function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} /> }
function Area(props: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea rows={3} {...props} /> }
function Button({ children, kind = 'dark', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { kind?: 'dark' | 'light' }) { return <button className={`button ${kind}`} {...props}>{children}</button> }
type TemplateOption = { value: string; label: string; swatch: string }
const regularTemplates: TemplateOption[] = [{value:'ribbon',label:'Ribbon',swatch:'linear-gradient(135deg,#ef3340 0 24%,#fff 24% 76%,#ef3340 76%)'},{value:'arch',label:'Arch',swatch:'linear-gradient(#174c43 0 34%,#fff 34%)'},{value:'minimal',label:'Minimal',swatch:'#f8f7f2'}]
const qrisCustomTemplates: TemplateOption[] = [{value:'classic',label:'Classic',swatch:'#f5f1e9'},{value:'noir',label:'Noir',swatch:'#191919'},{value:'terra',label:'Terra',swatch:'#d8a07c'},{value:'royal',label:'Royal',swatch:'#062b53'},{value:'sage',label:'Sage',swatch:'#b8cfb9'},{value:'cobalt',label:'Cobalt',swatch:'#0755c9'}]
const businessCustomTemplates: TemplateOption[] = [{value:'slate',label:'Slate',swatch:'#f4f4f1'},{value:'aurora',label:'Aurora',swatch:'#0b1b32'},{value:'terra-card',label:'Terra',swatch:'#e7b18e'},{value:'cobalt-card',label:'Cobalt',swatch:'#0755c9'}]
const menuCustomTemplates: TemplateOption[] = [{value:'botanical',label:'Botanical',swatch:'#8b5b3f'},{value:'bistro',label:'Bistro',swatch:'#163b35'},{value:'editorial',label:'Editorial',swatch:'#d9c6a3'}]
function TemplatePicker({ value, onChange, options, label }: { value: string; onChange: (value: string) => void; options: TemplateOption[]; label: string }) { return <div className="template-picker" role="radiogroup" aria-label={label}>{options.map(option => <button key={option.value} type="button" role="radio" aria-checked={value === option.value} className={value === option.value ? 'template-option active' : 'template-option'} onClick={() => onChange(option.value)}><span className="template-swatch" style={{ background: option.swatch }}/><span>{option.label}</span></button>)}</div> }
function TemplateGroups({ value, onChange, custom }: { value: string; onChange: (value: string) => void; custom: TemplateOption[] }) { return <div className="template-groups"><section><div className="template-heading"><b>Regular</b><span>Konsisten di semua fitur</span></div><TemplatePicker value={value} onChange={onChange} options={regularTemplates} label="Template Regular"/></section><section><div className="template-heading"><b>Custom</b><span>Khusus untuk fitur ini</span></div><TemplatePicker value={value} onChange={onChange} options={custom} label="Template Custom"/></section></div> }
async function shareOrCopy(title: string, text: string, url?: string) { try { if (navigator.share) await navigator.share({ title, text, url }); else await copy(url ? `${text}\n${url}` : text) } catch (error) { if (!(error instanceof DOMException && error.name === 'AbortError')) await copy(url ? `${text}\n${url}` : text) } }
function resizeImage(file: File, maxWidth = 720) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = reject; reader.onload = () => { const image = new Image(); image.onerror = reject; image.onload = () => { const scale = Math.min(1, maxWidth / image.width); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d')?.drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', .78)) }; image.src = String(reader.result) }; reader.readAsDataURL(file) }) }
async function downloadPdf(target: HTMLElement, filename: string) { const [{ jsPDF }, canvas] = await Promise.all([import('jspdf'), html2canvas(target, { scale: 2, backgroundColor: '#fff', useCORS: true })]); const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' }); const pageWidth = 190, pageHeight = 277, imageHeight = canvas.height * pageWidth / canvas.width, image = canvas.toDataURL('image/jpeg', .94); let remaining = imageHeight, y = 10; pdf.addImage(image, 'JPEG', 10, y, pageWidth, imageHeight); while (remaining > pageHeight) { remaining -= pageHeight; y = 10 - (imageHeight - remaining); pdf.addPage(); pdf.addImage(image, 'JPEG', 10, y, pageWidth, imageHeight) } pdf.save(filename) }

function Qr({ value, size = 220 }: { value: string; size?: number }) {
  const [src, setSrc] = useState('')
  useEffect(() => { let active = true; QRCode.toDataURL(value || 'microtools.id', { width: size, margin: 1, errorCorrectionLevel: 'M', color: { dark: '#161615', light: '#ffffff' } }).then(x => active && setSrc(x)); return () => { active = false } }, [value, size])
  return <img className="qr" width={size} height={size} src={src} alt="Kode QR" />
}
function ToolShell({ title, note, children }: { title: string; note: string; children: ReactNode }) { return <main className="tool-page"><button className="back" onClick={() => go('/')}>← Kembali</button><header className="tool-header"><h1>{title}</h1><p>{note}</p></header>{children}</main> }
function DownloadPanel({ target, file = 'microtools.png' }: { target: React.RefObject<HTMLElement | null>; file?: string }) { return <Button onClick={async () => { if (target.current) download((await html2canvas(target.current, { scale: 2, backgroundColor: '#fff' })).toDataURL('image/png'), file) }}>Unduh PNG</Button> }

function Home() { return <main className="home"><h1>microtools.id</h1><div className="tool-grid">{tools.map(([path, icon, name]) => <button key={path} className="tool-card" onClick={() => go(`/${path}`)}><span className="tool-icon">{icon}</span><span>{name}</span><b>→</b></button>)}</div></main> }

function Qris() {
  const [data, setData] = useState({ business: '', title: 'Pembayaran QRIS', note: '', color: '#ef3340', image: '', template: 'ribbon' }); const card = useRef<HTMLDivElement>(null)
  const change = (key: keyof typeof data, value: string) => setData({ ...data, [key]: value })
  return <ToolShell title="QRIS Designer" note="Buat tampilan QRIS siap cetak."><div className="workspace"><section className="form"><Field label="Template"><TemplateGroups value={data.template} onChange={value => change('template', value)} custom={qrisCustomTemplates}/></Field><Field label="Nama usaha"><Input value={data.business} onChange={e => change('business', e.target.value)} placeholder="Warung Makan Sederhana" /></Field><Field label="Judul"><Input value={data.title} onChange={e => change('title', e.target.value)} /></Field><Field label="Gambar QRIS"><Input type="file" accept="image/*" onChange={e => { const f = e.target.files?.[0]; if (f) { const r = new FileReader(); r.onload = () => change('image', String(r.result)); r.readAsDataURL(f) } }} /></Field><Field label="Catatan (opsional)"><Area value={data.note} onChange={e => change('note', e.target.value)} placeholder="Terima kasih atas pembayaran Anda" /></Field><Field label="Warna aksen"><Input type="color" value={data.color} onChange={e => change('color', e.target.value)} /></Field></section><section className="preview-wrap"><div ref={card} data-testid="qris-preview" className={`qris-card qris-${data.template}`} style={{ '--accent': data.color } as React.CSSProperties}><div className="qris-decor top"/><div className="qris-title">{data.title || 'Pembayaran QRIS'}</div><h2>{data.business || 'Nama Usaha'}</h2><div className="qris-image">{data.image ? <img src={data.image} alt="QRIS yang diunggah" /> : <span>Unggah gambar QRIS</span>}</div><p>{data.note || 'Terima kasih atas pembayaran Anda'}</p><div className="qris-decor bottom"/></div><div className="actions"><DownloadPanel target={card} file="qris-display.png"/><Button kind="light" onClick={print}>Cetak</Button></div></section></div></ToolShell>
}

function BusinessCard() {
  const [d, setD] = useState({ name: '', title: '', company: '', phone: '', email: '', website: '', instagram: '', linkedin: '', template: 'ribbon' }); const card = useRef<HTMLDivElement>(null)
  const set = (k: keyof typeof d, v: string) => setD({ ...d, [k]: v }); const vcard = `BEGIN:VCARD\nVERSION:3.0\nFN:${d.name}\nTITLE:${d.title}\nORG:${d.company}\nTEL;TYPE=CELL:${d.phone}\nEMAIL:${d.email}\nURL:${d.website}\nX-SOCIALPROFILE;TYPE=instagram:${d.instagram}\nX-SOCIALPROFILE;TYPE=linkedin:${d.linkedin}\nEND:VCARD`
  const profile = [d.name, d.title && `${d.title}${d.company ? ` di ${d.company}` : ''}`, d.phone, d.email, d.website, d.instagram && `Instagram: ${d.instagram}`, d.linkedin && `LinkedIn: ${d.linkedin}`].filter(Boolean).join('\n')
  return <ToolShell title="QR Business Card" note="Bagikan kontak profesional dalam satu QR."><div className="workspace"><section className="form"><Field label="Template"><TemplateGroups value={d.template} onChange={value => set('template', value)} custom={businessCustomTemplates}/></Field><div className="two-col">{([['name','Nama'],['title','Jabatan'],['company','Perusahaan'],['phone','WhatsApp / telepon'],['email','Email'],['website','Website'],['instagram','Instagram (opsional)'],['linkedin','LinkedIn (opsional)']] as [keyof typeof d, string][]).map(([k,l]) => <Field key={k} label={l}><Input value={d[k]} onChange={e => set(k,e.target.value)} /></Field>)}</div></section><section className="preview-wrap"><div ref={card} data-testid="business-preview" className={`business-card business-${d.template}`}><div className="business-copy"><small>{d.company || 'PERUSAHAAN'}</small><h2>{d.name || 'Nama Anda'}</h2><p className="business-role">{d.title || 'Jabatan'}</p><div className="contact-list"><span>☎ {d.phone || 'Nomor telepon'}</span><span>✉ {d.email || 'email@anda.com'}</span>{d.website && <span>⌘ {d.website}</span>}{d.instagram && <span>◎ {d.instagram}</span>}{d.linkedin && <span>in {d.linkedin}</span>}</div></div><div className="business-qr"><Qr value={vcard} size={132}/><small>SCAN KONTAK</small></div></div><div className="actions"><Button onClick={() => QRCode.toDataURL(vcard, { width: 900 }).then(x => download(x,'business-card-qr.png'))}>Unduh QR</Button><Button kind="light" onClick={() => download(`data:text/vcard;charset=utf-8,${encodeURIComponent(vcard)}`, 'kontak.vcf')}>Unduh vCard</Button><Button kind="light" onClick={() => copy(profile)}>Salin profil</Button><Button kind="light" onClick={() => shareOrCopy(d.name || 'Kontak', profile)}>Bagikan</Button></div></section></div></ToolShell>
}

function ItemRows({ items, setItems, descriptions = false, quantity = false }: { items: Item[]; setItems: (x: Item[]) => void; descriptions?: boolean; quantity?: boolean }) {
  const update = (i: number, k: keyof Item, v: string) => { const next = [...items]; next[i] = { ...next[i], [k]: k === 'price' || k === 'qty' ? Number(v) : v }; setItems(next) }
  return <div className="item-rows">{items.map((it, i) => <div className="item-row" key={i}><Input aria-label="Nama" value={it.name} onChange={e => update(i,'name',e.target.value)} placeholder="Nama item" />{quantity && <Input aria-label="Jumlah" type="number" min="1" value={it.qty} onChange={e => update(i,'qty',e.target.value)} placeholder="Qty" />}<Input aria-label="Harga" type="number" min="0" value={it.price || ''} onChange={e => update(i,'price',e.target.value)} placeholder="Harga" />{descriptions && <Input aria-label="Deskripsi" value={it.description || ''} onChange={e => update(i,'description',e.target.value)} placeholder="Deskripsi" />}<button className="icon-button" title="Hapus item" onClick={() => setItems(items.filter((_, n) => n !== i))}>×</button></div>)}<Button kind="light" type="button" onClick={() => setItems([...items, { name: '', ...(quantity ? { qty: 1 } : {}), price: 0, ...(descriptions ? { description: '' } : {}) }])}>+ Tambah item</Button></div>
}

function InvoiceReceipt({ receipt = false }: { receipt?: boolean }) {
  const [d, setD] = useState({ business: '', customer: '', number: receipt ? 'RCPT-001' : 'INV-001', date: today, tax: 0, note: '' }); const [items, setItems] = useState<Item[]>([{ name: '', qty: 1, price: 0 }]); const total = items.reduce((n, i) => n + (i.qty || 0) * i.price, 0), tax = total * d.tax / 100
  const set = (k: keyof typeof d, v: string | number) => setD({...d,[k]:v})
  const title = receipt ? 'Receipt Generator' : 'Invoice Generator'
  if (receipt) return <ToolShell title={title} note="Buat tanda terima sederhana siap cetak."><div className="workspace"><section className="form"><Field label="Nama usaha"><Input value={d.business} onChange={e=>set('business',e.target.value)}/></Field><Field label="Nama pelanggan (opsional)"><Input value={d.customer} onChange={e=>set('customer',e.target.value)}/></Field><div className="form-inline"><Field label="Nomor receipt"><Input value={d.number} onChange={e=>set('number',e.target.value)}/></Field><Field label="Tanggal"><Input type="date" value={d.date} onChange={e=>set('date',e.target.value)}/></Field></div><Field label="Item"><ItemRows items={items} setItems={setItems} quantity/></Field></section><section className="preview-wrap"><article className="document"><div className="document-top"><h2>RECEIPT</h2><span>{d.number}</span></div><h3>{d.business || 'Nama Usaha'}</h3><p>{d.customer ? `Untuk: ${d.customer}` : 'Pelanggan'} · {dateText(d.date)}</p><table><thead><tr><th>Item</th><th>Qty</th><th>Harga</th><th>Jumlah</th></tr></thead><tbody>{items.length ? items.map((i,n)=><tr key={n}><td>{i.name || '—'}</td><td>{i.qty}</td><td>{rupiah(i.price)}</td><td>{rupiah((i.qty || 0)*i.price)}</td></tr>) : <tr><td colSpan={4}>Belum ada item</td></tr>}</tbody></table><div className="totals"><span>Subtotal</span><b>{rupiah(total)}</b><strong>Total</strong><strong>{rupiah(total)}</strong></div></article><div className="actions"><Button onClick={print}>Cetak / Simpan PDF</Button></div></section></div></ToolShell>
  return <ToolShell title={title} note={receipt ? 'Buat tanda terima sederhana siap cetak.' : 'Buat invoice profesional dalam hitungan detik.'}><div className="workspace"><section className="form"><Field label="Nama usaha"><Input value={d.business} onChange={e=>set('business',e.target.value)} placeholder="Toko Sinar Jaya"/></Field><Field label="Nama pelanggan (opsional)"><Input value={d.customer} onChange={e=>set('customer',e.target.value)} placeholder="PT Maju Bersama"/></Field><div className="form-inline"><Field label={receipt ? 'Nomor receipt' : 'Nomor invoice'}><Input value={d.number} onChange={e=>set('number',e.target.value)}/></Field><Field label="Tanggal"><Input type="date" value={d.date} onChange={e=>set('date',e.target.value)}/></Field></div>{!receipt && <Field label="Pajak (%)"><Input type="number" min="0" max="100" value={d.tax} onChange={e=>set('tax',Math.min(100,Math.max(0,Number(e.target.value))))}/></Field>}<Field label="Item"><ItemRows items={items} setItems={setItems} quantity/></Field><Field label="Catatan (opsional)"><Area value={d.note} onChange={e=>set('note',e.target.value)} placeholder="Terima kasih atas kepercayaan Anda."/></Field></section><section className="preview-wrap"><article data-testid="invoice-preview" className="document invoice-document"><div className="invoice-heading"><div><small>DARI</small><h3>{d.business || 'Nama Usaha'}</h3></div><div><h2>{receipt ? 'RECEIPT' : 'INVOICE'}</h2><strong>{d.number || '—'}</strong></div></div><div className="invoice-meta"><div><small>{receipt ? 'DITERIMA DARI' : 'DITAGIHKAN KEPADA'}</small><b>{d.customer || 'Nama Pelanggan'}</b></div><div><small>TANGGAL</small><b>{dateText(d.date)}</b></div></div><table><thead><tr><th>Deskripsi</th><th>Qty</th><th>Harga</th><th>Jumlah</th></tr></thead><tbody>{items.length ? items.map((i,n)=><tr key={n}><td>{i.name || '—'}</td><td>{i.qty}</td><td>{rupiah(i.price)}</td><td>{rupiah((i.qty || 0)*i.price)}</td></tr>) : <tr><td colSpan={4}>Belum ada item</td></tr>}</tbody></table><div className="invoice-bottom"><p>{d.note || 'Terima kasih atas kepercayaan Anda.'}</p><div className="totals"><span>Subtotal</span><b>{rupiah(total)}</b>{!receipt && <><span>Pajak ({d.tax}%)</span><b>{rupiah(tax)}</b></>}<strong>Total</strong><strong>{rupiah(total + tax)}</strong></div></div></article><div className="actions"><Button onClick={print}>Cetak / Simpan PDF</Button></div></section></div></ToolShell>
}

function PriceList() { const [d,setD]=useState({business:'',title:'DAFTAR HARGA'}); const [items,setItems]=useState<Item[]>([{name:'',price:0,description:''}]); const panel=useRef<HTMLDivElement>(null); return <ToolShell title="Price List Generator" note="Buat daftar harga yang bersih dan siap dibagikan."><div className="workspace"><section className="form"><Field label="Nama usaha"><Input value={d.business} onChange={e=>setD({...d,business:e.target.value})}/></Field><Field label="Judul"><Input value={d.title} onChange={e=>setD({...d,title:e.target.value})}/></Field><Field label="Produk"><ItemRows items={items} setItems={setItems} descriptions/></Field></section><section className="preview-wrap"><article ref={panel} className="price-document"><p>{d.business || 'NAMA USAHA'}</p><h2>{d.title || 'DAFTAR HARGA'}</h2>{items.length ? items.map((i,n)=><div className="price-line" key={n}><div><b>{i.name || 'Nama produk'}</b><small>{i.description}</small></div><b>{rupiah(i.price)}</b></div>) : <p>Tambahkan produk untuk mulai membuat daftar harga.</p>}</article><div className="actions"><DownloadPanel target={panel} file="daftar-harga.png"/><Button kind="light" onClick={print}>Cetak / Simpan PDF</Button></div></section></div></ToolShell> }

type MenuData={business:string; title:string; whatsapp:string; items:Item[]; template?:string}
function MenuCard({ d, link, target }: { d: MenuData; link: string; target?: React.RefObject<HTMLElement | null> }) { return <article ref={target as React.RefObject<HTMLElement>} data-testid="menu-preview" className={`menu-card menu-${d.template || 'botanical'}`}><div className="menu-ornament">✦</div><small>{d.business || 'NAMA USAHA'}</small><h2>{d.title || 'MENU'}</h2><div className="menu-items">{d.items.length ? d.items.map((i,n)=><div className="menu-row" key={n}><div><b>{i.name || 'Nama menu'}</b><p>{i.description || 'Deskripsi singkat menu'}</p></div><b>{rupiah(i.price)}</b></div>) : <p className="empty-state">Tambahkan item untuk menampilkan menu.</p>}</div><div className="menu-qr"><Qr value={link} size={112}/><span>Scan untuk melihat menu</span></div></article> }
function Menu({ viewer = false }: { viewer?: boolean }) { const stored=viewer?decode<MenuData>(location.hash):null; const [d,setD]=useState<MenuData>(stored || {business:'',title:'Menu Pilihan',whatsapp:'',items:[{name:'',price:0,description:''}],template:'ribbon'}); const card=useRef<HTMLElement>(null); const link=`${location.origin}/menu#${encode(d)}`; if(viewer) return <PublicMenu d={d} catalog={false}/>; return <ToolShell title="QR Menu" note="Buat menu digital dengan tautan dan QR yang bisa dibagikan."><div className="workspace"><section className="form"><Field label="Template"><TemplateGroups value={d.template || 'ribbon'} onChange={template=>setD({...d,template})} custom={menuCustomTemplates}/></Field><Field label="Nama usaha"><Input value={d.business} onChange={e=>setD({...d,business:e.target.value})} placeholder="Kedai Kopi Kita"/></Field><Field label="Judul menu"><Input value={d.title} onChange={e=>setD({...d,title:e.target.value})}/></Field><Field label="WhatsApp pemesanan (opsional)"><Input value={d.whatsapp} onChange={e=>setD({...d,whatsapp:e.target.value})} placeholder="62812..."/></Field><Field label="Menu"><ItemRows items={d.items} setItems={items=>setD({...d,items})} descriptions/></Field></section><section className="preview-wrap"><MenuCard d={d} link={link} target={card}/><div className="actions"><Button onClick={()=>copy(link)}>Salin link</Button><Button kind="light" onClick={()=>window.open(link,'_blank')}>Buka menu</Button><Button kind="light" onClick={()=>shareOrCopy(d.business || 'Menu', 'Lihat menu kami', link)}>Bagikan</Button><Button kind="light" onClick={()=>QRCode.toDataURL(link,{width:900}).then(x=>download(x,'menu-qr.png'))}>Unduh QR</Button><DownloadPanel target={card} file="menu.png"/></div></section></div></ToolShell> }

type CatalogData={store:string; whatsapp:string; items:Item[]}
function Catalog({ viewer = false }: { viewer?: boolean }) { const stored=viewer?decode<CatalogData>(location.hash):null; const [d,setD]=useState<CatalogData>(stored || {store:'',whatsapp:'',items:[{name:'',price:0,description:'',image:''}]}); const catalogRef=useRef<HTMLDivElement>(null); const setItems=(items:Item[])=>setD({...d,items}); const addImage=async(i:number,file?:File)=>{if(!file)return;const next=[...d.items];next[i]={...next[i],image:await resizeImage(file)};setItems(next)}; const link=`${location.origin}/catalog#${encode(d)}`; if(viewer)return <PublicMenu d={d} catalog/>; return <ToolShell title="Catalog Maker" note="Buat katalog produk sederhana untuk pelanggan."><div className="workspace"><section className="form"><Field label="Nama toko"><Input value={d.store} onChange={e=>setD({...d,store:e.target.value})} placeholder="Toko Fashion Kita"/></Field><Field label="WhatsApp"><Input value={d.whatsapp} onChange={e=>setD({...d,whatsapp:e.target.value})} placeholder="62812..."/></Field><Field label="Produk"><ItemRows items={d.items} setItems={setItems} descriptions/>{d.items.map((_,i)=><Field key={i} label={`Foto produk ${i+1} (opsional)`}><Input type="file" accept="image/*" onChange={e=>addImage(i,e.target.files?.[0])}/></Field>)}</Field></section><section className="preview-wrap"><div ref={catalogRef}><CatalogCards d={d}/></div><div className="share-link"><span>Link katalog</span><code>{link}</code></div><div className="actions"><Button onClick={()=>copy(link)}>Salin link</Button><Button kind="light" onClick={()=>window.open(link,'_blank')}>Buka katalog</Button><Button kind="light" onClick={()=>shareOrCopy(d.store || 'Katalog', 'Lihat katalog produk kami', link)}>Bagikan</Button><Button kind="light" onClick={()=>catalogRef.current&&downloadPdf(catalogRef.current,'katalog.pdf')}>Unduh PDF</Button><Button kind="light" onClick={()=>download(`data:text/html;charset=utf-8,${encodeURIComponent(`<!doctype html><meta charset="utf-8"><title>${d.store || 'Katalog'}</title><meta http-equiv="refresh" content="0;url=${link}"><p><a href="${link}">Buka katalog</a></p>`)}`,'katalog.html')}>Unduh HTML</Button></div></section></div></ToolShell> }

function CatalogCards({ d }: { d: CatalogData }) { return <article data-testid="catalog-preview" className="catalog"><header><div className="store-mark">{(d.store || 'T').slice(0,1).toUpperCase()}</div><div><small>KATALOG</small><h2>{d.store || 'Nama Toko'}</h2></div><span>{d.items.length} produk</span></header><div className="catalog-grid">{d.items.length?d.items.map((i,n)=><div className="product" key={n}>{i.image?<img src={i.image} alt={i.name}/>:<div className="product-image">FOTO PRODUK</div>}<b>{i.name || 'Nama produk'}</b><p>{i.description || 'Deskripsi produk'}</p><strong>{rupiah(i.price)}</strong>{d.whatsapp&&<a href={`https://wa.me/${cleanPhone(d.whatsapp)}?text=${encodeURIComponent(`Halo, saya ingin pesan ${i.name}`)}`} target="_blank" rel="noreferrer">Pesan via WhatsApp</a>}</div>):<p className="empty-state">Belum ada produk.</p>}</div></article> }
function PublicMenu({ d, catalog }: { d: MenuData | CatalogData; catalog: boolean }) { const menu=d as MenuData; return <main className="public-page">{catalog?<CatalogCards d={d as CatalogData}/>:<><MenuCard d={menu} link={location.href}/>{menu.whatsapp&&<div className="public-action"><a className="button dark" href={`https://wa.me/${cleanPhone(menu.whatsapp)}`} target="_blank" rel="noreferrer">Pesan via WhatsApp</a></div>}</>}</main> }

function LinkQr({ type }: { type: 'whatsapp'|'maps'|'wifi' }) { const [d,setD]=useState(type==='whatsapp'?{phone:'',message:''}:type==='maps'?{url:''}:{ssid:'',password:'',security:'WPA',hidden:false}); let value=''; if(type==='whatsapp'){const x=d as {phone:string;message:string};value=x.phone?`https://wa.me/${cleanPhone(x.phone)}?text=${encodeURIComponent(x.message)}`:''} if(type==='maps')value=(d as {url:string}).url; if(type==='wifi'){const x=d as {ssid:string;password:string;security:string;hidden:boolean}; const esc=(v:string)=>v.replace(/([\\;,:”])/g,'\\$1');value=`WIFI:T:${x.security};S:${esc(x.ssid)};P:${x.security==='nopass'?'':esc(x.password)};H:${x.hidden?'true':'false'};;`} const title=type==='whatsapp'?'WhatsApp Link Generator':type==='maps'?'Google Maps QR':'WiFi QR'; const note=type==='whatsapp'?'Buat link WhatsApp siap klik dan kode QR.':type==='maps'?'Ubah tautan Google Maps menjadi kode QR.':'Buat QR untuk tersambung ke WiFi dengan cepat.'; const update=(key:string,val:string|boolean)=>setD({...d,[key]:val} as typeof d); return <ToolShell title={title} note={note}><div className="workspace compact"><section className="form">{type==='whatsapp'&&<><Field label="Nomor WhatsApp"><Input value={(d as any).phone} onChange={e=>update('phone',e.target.value)} placeholder="62812..."/></Field><Field label="Pesan awal"><Area value={(d as any).message} onChange={e=>update('message',e.target.value)} placeholder="Halo, saya ingin bertanya..."/></Field></>}{type==='maps'&&<Field label="Google Maps URL"><Input type="url" value={(d as any).url} onChange={e=>update('url',e.target.value)} placeholder="https://maps.google.com/..."/></Field>}{type==='wifi'&&<><Field label="Nama WiFi (SSID)"><Input value={(d as any).ssid} onChange={e=>update('ssid',e.target.value)}/></Field><Field label="Password"><Input type="password" value={(d as any).password} onChange={e=>update('password',e.target.value)}/></Field><Field label="Jenis keamanan"><select value={(d as any).security} onChange={e=>update('security',e.target.value)}><option value="WPA">WPA/WPA2</option><option value="WEP">WEP</option><option value="nopass">Tanpa password</option></select></Field><label className="check"><Input type="checkbox" checked={(d as any).hidden} onChange={e=>update('hidden',e.target.checked)}/> Jaringan tersembunyi</label></>}</section><section className="preview-wrap qr-preview"><Qr value={value}/>{value&&<code>{type==='wifi'?value:value}</code>}<div className="actions">{type!=='wifi'&&<Button onClick={()=>copy(value)}>Salin {type==='whatsapp'?'link':'URL'}</Button>} {type!=='wifi'&&<Button kind="light" onClick={()=>window.open(value,'_blank')}>Buka</Button>}<Button kind={type==='wifi'?'dark':'light'} onClick={()=>QRCode.toDataURL(value||'microtools.id',{width:900}).then(x=>download(x,`${type}-qr.png`))}>Unduh QR</Button>{type==='wifi'&&<Button kind="light" onClick={print}>Cetak</Button>}</div></section></div></ToolShell> }

export default function App() { const [path,setPath]=useState(location.pathname); useEffect(()=>{const fn=()=>setPath(location.pathname);addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn)},[]); if(path==='/menu')return <Menu viewer/>;if(path==='/catalog'&&location.hash)return <Catalog viewer/>; const page:Record<string,ReactNode>={'/qris-designer':<Qris/>,'/qr-business-card':<BusinessCard/>,'/invoice':<InvoiceReceipt/>,'/receipt':<InvoiceReceipt receipt/>,'/price-list':<PriceList/>,'/qr-menu':<Menu/>,'/catalog':<Catalog/>,'/whatsapp':<LinkQr type="whatsapp"/>,'/google-maps-qr':<LinkQr type="maps"/>,'/wifi-qr':<LinkQr type="wifi"/>};return page[path]||<Home/> }
